server:
  port:80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/brain-science-research?serverTimeout=UTC
      username: root
      password: dream010923**
mybatis-plus:
  global-config:
    db-config:
      id-type: auto